require("config.lazy")
require("config.theme")
require("config.nvim-tree")
require("config.telescope")
require("config.diagnostic")
require("config.completion")
require("config.lsp")
require("config.treesitter")
